In [1]:
import pandas as pd 
import numpy as np

In [2]:
vendas = pd.read_excel("C:/Users/conta/Desktop/Projeto D3.js/vendas.xlsx")

In [3]:
print(vendas.isnull().sum())

ID_Pedido       0
Data_Pedido     0
ID_Cliente      0
Segmento        0
Regiao          0
Pais            0
Product ID      0
Categoria       0
SubCategoria    0
Total_Vendas    0
Quantidade      0
Desconto        0
Lucro           0
Prioridade      0
dtype: int64

In [9]:
vendas.describe()

       Total_Vendas    Quantidade      Desconto         Lucro
count  51290.000000  51290.000000  51290.000000  51290.000000
mean     246.490581      3.476545      0.142908     28.610982
std      487.565361      2.278766      0.212280    174.340972
min        0.444000      1.000000      0.000000  -6599.978000
25%       30.758625      2.000000      0.000000      0.000000
50%       85.053000      3.000000      0.000000      9.240000
75%      251.053200      5.000000      0.200000     36.810000
max    22638.480000     14.000000      0.850000   8399.976000

In [8]:
vendas.head(10)

,ID_Pedido,Data_Pedido,ID_Cliente,Segmento,Regiao,Pais,Product ID,Categoria,SubCategoria,Total_Vendas,Quantidade,Desconto,Lucro,Prioridade
0,CA-2012-124891,31-07-2012,RH-19495,Consumidor,New York,United States,TEC-AC-10003033,Tecnologia,Accessories,2309.650,7,0.0,762.1845,Critico
1,IN-2013-77878,05-02-2013,JR-16210,Corporativo,New South Wales,Australia,FUR-CH-10003950,Moveis,Chairs,3709.395,9,0.1,-288.7650,Critico
2,IN-2013-71249,17-10-2013,CR-12730,Consumidor,Queensland,Australia,TEC-PH-10004664,Tecnologia,Phones,5175.171,9,0.1,919.9710,Medio
3,ES-2013-1579342,28-01-2013,KM-16375,Home Office,Berlin,Germany,TEC-PH-10004583,Tecnologia,Phones,2892.510,5,0.1,-96.5400,Medio
4,SG-2013-4320,05-11-2013,RH-9495,Consumidor,Dakar,Senegal,TEC-SHA-10000501,Tecnologia,Copiers,2832.960,8,0.0,311.5200,Critico
5,IN-2013-42360,28-06-2013,JM-15655,Corporativo,New South Wales,Australia,TEC-PH-10000030,Tecnologia,Phones,2862.675,5,0.1,763.2750,Critico
6,IN-2011-81826,07-11-2011,TS-21340,Consumidor,Wellington,New Zealand,FUR-CH-10004050,Moveis,Chairs,1822.080,4,0.0,564.8400,Critico
7,IN-2012-86369,14-04-2012,MB-18085,Consumidor,Waikato,New Zealand,FUR-TA-10002958,Moveis,Tables,5244.840,6,0.0,996.4800,Alto
8,CA-2014-135909,14-10-2014,JW-15220,Corporativo,California,United States,OFF-BI-10003527,Suprimentos,Binders,5083.960,5,0.2,1906.4850,Baixo
9,CA-2012-116638,28-01-2012,JH-15985,Consumidor,North Carolina,United States,FUR-TA-10000198,Moveis,Tables,4297.644,13,0.4,-1862.3124,Critico

In [25]:
vendas['Data_Pedido'] = pd.to_datetime(vendas['Data_Pedido'], format='%d-%m-%Y')

vendas['Mes'] = vendas['Data_Pedido'].dt.month
vendas['Ano'] = vendas['Data_Pedido'].dt.year

vendas.head(10)

,ID_Pedido,Data_Pedido,ID_Cliente,Segmento,Regiao,Pais,Product ID,Categoria,SubCategoria,Total_Vendas,Quantidade,Desconto,Lucro,Prioridade,Mes,Ano
0,CA-2012-124891,2012-07-31,RH-19495,Consumidor,New York,United States,TEC-AC-10003033,Tecnologia,Accessories,2309.650,7,0.0,762.1845,Critico,7,2012
1,IN-2013-77878,2013-02-05,JR-16210,Corporativo,New South Wales,Australia,FUR-CH-10003950,Moveis,Chairs,3709.395,9,0.1,-288.7650,Critico,2,2013
2,IN-2013-71249,2013-10-17,CR-12730,Consumidor,Queensland,Australia,TEC-PH-10004664,Tecnologia,Phones,5175.171,9,0.1,919.9710,Medio,10,2013
3,ES-2013-1579342,2013-01-28,KM-16375,Home Office,Berlin,Germany,TEC-PH-10004583,Tecnologia,Phones,2892.510,5,0.1,-96.5400,Medio,1,2013
4,SG-2013-4320,2013-11-05,RH-9495,Consumidor,Dakar,Senegal,TEC-SHA-10000501,Tecnologia,Copiers,2832.960,8,0.0,311.5200,Critico,11,2013
5,IN-2013-42360,2013-06-28,JM-15655,Corporativo,New South Wales,Australia,TEC-PH-10000030,Tecnologia,Phones,2862.675,5,0.1,763.2750,Critico,6,2013
6,IN-2011-81826,2011-11-07,TS-21340,Consumidor,Wellington,New Zealand,FUR-CH-10004050,Moveis,Chairs,1822.080,4,0.0,564.8400,Critico,11,2011
7,IN-2012-86369,2012-04-14,MB-18085,Consumidor,Waikato,New Zealand,FUR-TA-10002958,Moveis,Tables,5244.840,6,0.0,996.4800,Alto,4,2012
8,CA-2014-135909,2014-10-14,JW-15220,Corporativo,California,United States,OFF-BI-10003527,Suprimentos,Binders,5083.960,5,0.2,1906.4850,Baixo,10,2014
9,CA-2012-116638,2012-01-28,JH-15985,Consumidor,North Carolina,United States,FUR-TA-10000198,Moveis,Tables,4297.644,13,0.4,-1862.3124,Critico,1,2012

In [30]:
'''Deletando conlunas'''
vendas = vendas.drop(columns=['Data_Pedido'])

In [28]:
meses = {
    1: 'Janeiro', 2: 'Fevereiro', 3: 'Março', 4: 'Abril',
    5: 'Maio', 6: 'Junho', 7: 'Julho', 8: 'Agosto',
    9: 'Setembro', 10: 'Outubro', 11: 'Novembro', 12: 'Dezembro'
}

vendas['Mes'] = vendas['Data_Pedido'].dt.month.map(meses)

In [31]:
vendas.head(10)

,ID_Pedido,ID_Cliente,Segmento,Regiao,Pais,Product ID,Categoria,SubCategoria,Total_Vendas,Quantidade,Desconto,Lucro,Prioridade,Mes,Ano
0,CA-2012-124891,RH-19495,Consumidor,New York,United States,TEC-AC-10003033,Tecnologia,Accessories,2309.650,7,0.0,762.1845,Critico,Julho,2012
1,IN-2013-77878,JR-16210,Corporativo,New South Wales,Australia,FUR-CH-10003950,Moveis,Chairs,3709.395,9,0.1,-288.7650,Critico,Fevereiro,2013
2,IN-2013-71249,CR-12730,Consumidor,Queensland,Australia,TEC-PH-10004664,Tecnologia,Phones,5175.171,9,0.1,919.9710,Medio,Outubro,2013
3,ES-2013-1579342,KM-16375,Home Office,Berlin,Germany,TEC-PH-10004583,Tecnologia,Phones,2892.510,5,0.1,-96.5400,Medio,Janeiro,2013
4,SG-2013-4320,RH-9495,Consumidor,Dakar,Senegal,TEC-SHA-10000501,Tecnologia,Copiers,2832.960,8,0.0,311.5200,Critico,Novembro,2013
5,IN-2013-42360,JM-15655,Corporativo,New South Wales,Australia,TEC-PH-10000030,Tecnologia,Phones,2862.675,5,0.1,763.2750,Critico,Junho,2013
6,IN-2011-81826,TS-21340,Consumidor,Wellington,New Zealand,FUR-CH-10004050,Moveis,Chairs,1822.080,4,0.0,564.8400,Critico,Novembro,2011
7,IN-2012-86369,MB-18085,Consumidor,Waikato,New Zealand,FUR-TA-10002958,Moveis,Tables,5244.840,6,0.0,996.4800,Alto,Abril,2012
8,CA-2014-135909,JW-15220,Corporativo,California,United States,OFF-BI-10003527,Suprimentos,Binders,5083.960,5,0.2,1906.4850,Baixo,Outubro,2014
9,CA-2012-116638,JH-15985,Consumidor,North Carolina,United States,FUR-TA-10000198,Moveis,Tables,4297.644,13,0.4,-1862.3124,Critico,Janeiro,2012

In [32]:
vendas.to_excel('vendas_Limpo.xlsx', index=False)